const MAX_VISIBLE_MOVIES_LARGE = 16;
const MAX_VISIBLE_MOVIES_MEDIUM = 12;
const MAX_VISIBLE_MOVIES_SMALL = 8;
const MAX_VISIBLE_MOVIES_XS = 5;
const SHORT_FILM_DURATION = 40;

export { MAX_VISIBLE_MOVIES_XS, MAX_VISIBLE_MOVIES_SMALL, MAX_VISIBLE_MOVIES_MEDIUM, MAX_VISIBLE_MOVIES_LARGE, SHORT_FILM_DURATION};
